### ISSUE TITLE
Benefit of running on a single server?

### ISSUE THREAD

**Issue by DarrylD** [dimapaloskin/dev-gateway#8]
Just curious, any benefits for running all the microservices on a single server opposed to each having their own?

**Comment by dimapaloskin** [comment]
It is gateway for development. Sure, for the production code you need to use separate containers (deploys in `now.sh` terms). It is just a gateway which help you orchestrate all your microservices in development environment.

**Comment by DarrylD** [comment]
Ok, I was looking for this and didn't know it :) Thanks!
